export const ADMIN_ROLE = "ADMIN";
export const USER_ROLE = "USER";
export const WRITER_ROLE = "WRITER";
export const COMMUNITY_ADMIN_ROLE = "COMMUNITY_ADMIN";
export const COMMUNITY_MODERATOR_ROLE = "COMMUNITY_MODERATOR";
